Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2018-09, with the labels that each got.

#890 [Part 1 of #758] Remove pod-culler remnants
  chartpress.yaml
  images/hub/jupyterhub_config.py
  jupyterhub/templates/_helpers.tpl
  jupyterhub/templates/pod-culler/deployment.yaml
  jupyterhub/templates/pod-culler/rbac.yaml
  jupyterhub/values.yaml
Labels: needs: pr review

#891 [Part 2 of #758] user-scheduler added
  images/hub/jupyterhub_config.py
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/configmap.yaml
  jupyterhub/templates/scheduling/user-scheduler/_helpers.tpl
  jupyterhub/templates/scheduling/user-scheduler/configmap.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement, needs: pr review

#910 Support singleuser extraContainer
  images/hub/jupyterhub_config.py
  jupyterhub/templates/hub/configmap.yaml
  jupyterhub/templates/image-puller/_daemonset-helper.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement
