Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2020-10, with the labels that each got.

#1436 add Auth0 configuration documentation
  doc/source/administrator/authentication.rst
Labels: documentation

#1564 AWS documentation fixes
  doc/source/amazon/step-zero-aws.rst
  doc/source/conf.py
Labels: documentation

#1796 Docs: fix some sphinx warnings
  doc/source/amazon/step-zero-aws.rst
  doc/source/setup-jupyterhub/setup-helm2.rst
Labels: documentation

#1802 hub image: bump kubespawner to 0.14.0
  images/hub/dependencies
  images/hub/requirements.in
  images/hub/requirements.txt
Labels: maintenance

#1805 Soft deprecate singleuser.cloudMetadata.enabled in favor of blockWithIptables
  doc/source/administrator/security.md
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/image-puller/_daemonset-helper.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: maintenance

#1808 Fix same functionality for proxy.traefik.extraEnv as other extraEnv
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: bug

#1816 CI: fix RTD builds on push to master
  .readthedocs.yml
  doc/doc-requirements.txt
  doc/source/conf.py
Labels: maintenance

#1815 README.md: badges for the helm chart repo to go directly to the relevant view
  README.md
Labels: documentation

#1817 prePuller: fix recently introduced regression
  jupyterhub/templates/image-puller/_daemonset-helper.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: bug

#1818 Added config prePuller.pullProfileListImages
  jupyterhub/schema.yaml
  jupyterhub/templates/image-puller/_daemonset-helper.yaml
  jupyterhub/values.yaml
Labels: enhancement

#1813 Added config option: proxy.chp.extraCommandLineFlags
  jupyterhub/schema.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement

#1807 deprecation: warn when proxy.https is modified and proxy.https.enabled=true
  jupyterhub/templates/NOTES.txt
Labels: breaking, maintenance

#1798 Set container securityContext by default
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/image-puller/_daemonset-helper.yaml
  jupyterhub/templates/image-puller/job.yaml
  jupyterhub/templates/proxy/autohttps/_configmap-traefik.yaml
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/values.yaml
Labels: breaking, bug, enhancement

#1826 Revert recent removal of image-pulling related to cloudMetadata blocker
  jupyterhub/templates/image-puller/_daemonset-helper.yaml
Labels: maintenance

#1828 CI: reorder ci jobs to provide relevant feedback quickly
  .travis.yml
Labels: maintenance

#1827 Add nodeSelector and tolerations config for all pods of Helm chart
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/image-puller/job.yaml
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
  tools/templates/yamllint-config.yaml
Labels: enhancement

#1830 Add retryable HTTP client to image-awaiter
  images/image-awaiter/Dockerfile
  images/image-awaiter/daemonset.go
  images/image-awaiter/go.mod
  images/image-awaiter/go.sum
Labels: bug

#1832 Add schema.yaml and validate.py to .helmignore
  jupyterhub/.helmignore
Labels: maintenance

#1848 CI: bump k3s and helm versions
  .travis.yml
Labels: maintenance

#1820 Add maintainers / owners to register with Artifact Hub
  artifacthub-repo.yml
  jupyterhub/Chart.yaml
Labels: maintenance

#1850 Provide links to Hub23 deployment guide
  doc/source/microsoft/step-zero-azure-autoscale.rst
  doc/source/microsoft/step-zero-azure.rst
Labels: documentation

#1837 user-scheduler: let image locality etc matter again
  .travis.yml
  ci/common
  dev-config.yaml
  jupyterhub/values.yaml
  tests/conftest.py
Labels: bug

#1794 Support chart wide and pod specific config of imagePullSecrets
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/schema.yaml
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/_helpers.tpl
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/hub/image-credentials-secret.yaml
  jupyterhub/templates/image-pull-secret.yaml
  jupyterhub/templates/image-puller/_daemonset-helper.yaml
  jupyterhub/templates/image-puller/job.yaml
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/templates/singleuser/image-credentials-secret.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: breaking, enhancement

#1852 Add proxy.service.extraPorts to add ports to the k8s Service proxy-public
  jupyterhub/schema.yaml
  jupyterhub/templates/proxy/service.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement

#1825 Change doc structure
  .gitignore
  doc/source/community/additional-resources.rst
  doc/source/community/index.rst
  doc/source/community/users-list.md
  doc/source/conf.py
  doc/source/index.rst
  doc/source/jupyterhub/customization.rst
  doc/source/jupyterhub/customizing/extending-jupyterhub.rst
  doc/source/jupyterhub/customizing/user-environment.rst
  doc/source/jupyterhub/customizing/user-management.md
  doc/source/jupyterhub/customizing/user-resources.rst
  doc/source/jupyterhub/customizing/user-storage.md
  doc/source/jupyterhub/index.rst
  doc/source/jupyterhub/installation.rst
  doc/source/jupyterhub/uninstall.rst
  doc/source/kubernetes/amazon/efs_storage.rst
  doc/source/kubernetes/amazon/step-zero-aws-eks.rst
  doc/source/kubernetes/amazon/step-zero-aws.rst
  doc/source/kubernetes/digital-ocean/step-zero-digital-ocean.rst
  doc/source/kubernetes/google/step-zero-gcp.rst
  doc/source/kubernetes/ibm/step-zero-ibm.rst
  doc/source/kubernetes/index.rst
  doc/source/kubernetes/microsoft/step-zero-azure-autoscale.rst
  doc/source/kubernetes/microsoft/step-zero-azure.rst
  doc/source/kubernetes/openstack/.gitkeep
  doc/source/kubernetes/other-infrastructure/.gitkeep
  doc/source/kubernetes/ovh/step-zero-ovh.rst
  doc/source/kubernetes/redhat/step-zero-openshift.rst
  doc/source/kubernetes/setup-helm.rst
  doc/source/kubernetes/setup-helm2.rst
  doc/source/kubernetes/setup-kubernetes.rst
  doc/source/resources/community.rst
  doc/source/resources/glossary.rst
  doc/source/resources/index.rst
  doc/source/resources/reference-docs.rst
  doc/source/resources/reference.txt
  doc/source/resources/tools.rst
  doc/source/setup-jupyterhub/index.rst
Labels: documentation

#1868 Bump KubeSpawner to 0.14.1 to fix a bug in 0.14.0 about image_pull_secrets
  images/hub/requirements.txt
Labels: bug

#1840 hub.command and hub.args configuration added
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement

#1795 CHANGELOG.md: prep for 0.10.0-beta.1
  CHANGELOG.md
Labels: documentation

#1873 Dependency: bump proxy pods image of CHP to 4.2.2 for bugfixes and docker image dependency updates
  jupyterhub/values.yaml
Labels: maintenance

#1881 Remove globus_sdk and update various Docker images
  images/hub/Dockerfile
  images/hub/requirements.in
  images/hub/requirements.txt
  images/network-tools/Dockerfile
  images/singleuser-sample/Dockerfile
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#1884 use jupyterhub 1.2.0
  chartpress.yaml
  images/hub/requirements.txt
  jupyterhub/Chart.yaml
Labels: dependencies, maintenance

#1889 jupyterhub 1.2.1
  chartpress.yaml
  images/hub/requirements.in
  images/hub/requirements.txt
  jupyterhub/Chart.yaml
Labels: bug, dependencies

#1892 Add securityContext to all image-puller pods' containers
  jupyterhub/templates/image-puller/_daemonset-helper.yaml
Labels: bug

#1895 Avoid harmless error in user-scheduler
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
Labels: maintenance
