Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2020-12, with the labels that each got.

#1932 hub image: bump ltiauthenticator to 1.0.0 and oauthenticator to 0.12.3
  images/hub/requirements.txt
Labels: dependencies, maintenance

#1942 ci: cronjob to scan images for known vulnerabilities
  .github/workflows/vuln-scan.yaml
  README.md
Labels: maintenance

#1945 Helm template linting - remove extra space
  jupyterhub/templates/proxy/service.yaml
Labels: maintenance

#1949 ci: let dependabot update used GitHub action's versions
  .github/dependabot.yaml
Labels: maintenance

#1950 Fix failure to block insecure metadata server IP
  jupyterhub/files/hub/jupyterhub_config.py
Labels: bug

#1953 ci: vuln scan fix
  .github/workflows/vuln-scan.yaml
Labels: maintenance

#1948 ci: let dependabot update jupyterhub, replace JUPYTERHUB_VERSION with PIP_OVERRIDES
  chartpress.yaml
  images/hub/Dockerfile
  images/hub/requirements.in
  images/singleuser-sample/Dockerfile
Labels: maintenance

#1957 Adds a linebreak
  doc/source/jupyterhub/customizing/extending-jupyterhub.rst
Labels: documentation

#1956 ci: Test against k8s 1.20
  .github/workflows/test.yml
Labels: maintenance

#1963 ci: remove yaml anchors from dependabot config
  .github/dependabot.yaml
Labels: maintenance

#1964 ci: help dependabot only trigger one set of tests
  .github/workflows/test.yml
Labels: maintenance

#1967 ci: full_namespace_report function improved
  .github/workflows/test.yml
  ci/common
Labels: maintenance

#1971 ci: full_namespace_report improvements for restartCount > 0
  ci/common
Labels: maintenance

#1973 ci: use k3s-channel instead of k3s-version
  .github/workflows/test.yml
Labels: maintenance
