Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2020-11, with the labels that each got.

#1883 prePuller.extraTolerations added for the image-puller daemonsets
  jupyterhub/schema.yaml
  jupyterhub/templates/image-puller/_daemonset-helper.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement

#1669 removal: contributors script
  RELEASE.md
  tools/contributors.py
Labels: maintenance

#1904 CI: make upgrades more robust and skip 1m precautionary sleep
  .github/workflows/test.yml
  ci/common
  ci/publish
Labels: maintenance

#1911 Require helm v2.16.0 explicitly and minor CI updates
  ci/publish
  jupyterhub/Chart.yaml
  tools/templates/lint-and-validate.py
Labels: maintenance

#1913 Add changelog for 0.10.3 release
  CHANGELOG.md
Labels: documentation

#1924 image: bump JupyterHub to 1.2.2 from 1.2.1 for bugfixes
  chartpress.yaml
  images/hub/requirements.in
  images/hub/requirements.txt
  jupyterhub/Chart.yaml
Labels: bug, dependencies
