Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2021-02, with the labels that each got.

#2006 Allow extraFiles to be injected to hub / singleuser pods and automatically load config in /usr/local/etc/jupyterhub_config.d
  dev-config.yaml
  images/hub/Dockerfile
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/files/hub/z2jh.py
  jupyterhub/schema.yaml
  jupyterhub/templates/_helpers.tpl
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/hub/secret.yaml
  jupyterhub/templates/singleuser/secret.yaml
  jupyterhub/values.yaml
  tests/test_spawn.py
  tools/templates/lint-and-validate-values.yaml
Labels: new

#2001 dep: bump traefik from v2.3.7 to v2.4.1
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#2021 ci: use jupyterhub/action-k8s-await-workloads
  .github/workflows/test-chart.yaml
Labels: ci

#2023 fix: load only .py files in jupyterhub_config.d folder
  jupyterhub/files/hub/jupyterhub_config.py
Labels: bug

#2005 Require k8s 1.17+ to reduce complexity
  .github/workflows/test-chart.yaml
  jupyterhub/Chart.yaml
Labels: breaking, maintenance

#2027 Allow ingress.hosts to be omitted for a more generic rule
  .github/workflows/test-chart.yaml
  doc/source/administrator/advanced.md
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/ingress.yaml
Labels: enhancement

#2031 Fix schema.yaml jsonschema syntax errors
  jupyterhub/schema.yaml
Labels: documentation

#2032 traefik / autohttps: bump v2.4.2 to v2.4.3
  jupyterhub/values.yaml
Labels: dependencies

#2035 docs: package chart specific README.md with the chart
  jupyterhub/README.md
Labels: documentation

#2036 hub image build: fix use of PIP_OVERRIDES arg
  images/hub/Dockerfile
Labels: bug

#1995 Remove deprecated user-scheduler config
  jupyterhub/files/userscheduler-defaultpolicy.yaml
  jupyterhub/templates/scheduling/user-scheduler/configmap.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
Labels: maintenance

#2033 values.schema.json ships with chart and configuration reference now covers all options
  .github/workflows/publish.yml
  .github/workflows/test-chart.yaml
  .gitignore
  doc/source/administrator/advanced.md
  doc/source/administrator/security.md
  doc/source/conf.py
  jupyterhub/.helmignore
  jupyterhub/schema.yaml
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/hub/service.yaml
  jupyterhub/templates/ingress.yaml
  jupyterhub/templates/proxy/autohttps/_configmap-dynamic.yaml
  jupyterhub/templates/proxy/secret.yaml
  jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/validate.py
  jupyterhub/values.yaml
  tools/compare-values-schema-content.py
  tools/generate-json-schema.py
  tools/templates/lint-and-validate-values.yaml
  tools/validate-against-schema.py
Labels: breaking, documentation, enhancement

#2037 ci: install pyyaml before publishing to generate json schema
  .github/workflows/publish.yml
Labels: ci

#2039 pdb: default to maxUnavailable=1 instead of minAvailable=1
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/pdb.yaml
  jupyterhub/templates/proxy/autohttps/pdb.yaml
  jupyterhub/templates/proxy/pdb.yaml
  jupyterhub/templates/scheduling/user-scheduler/pdb.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: bug

#2038 fix: imagePullSecret.enabled to work alongside imagePullSecret.create
  jupyterhub/templates/_helpers.tpl
Labels: bug

#2047 traefik/autohttps: bump traefik to v2.4.5 from v2.4.2
  jupyterhub/README.md
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#2049 Fix Chart.yaml annotations for artifacthub.io image scanning
  .github/workflows/publish.yml
Labels: ci

#2052 vuln-scan: fix all fixable vulns, and bugfix automation, and bump singleuser-sample
  .github/workflows/vuln-scan.yaml
  images/hub/Dockerfile
  images/image-awaiter/Dockerfile
  images/network-tools/Dockerfile
  images/secret-sync/Dockerfile
  images/singleuser-sample/Dockerfile
Labels: ci

#2054 docs: helm3 compliance, avoid specification of chart versions
  doc/source/administrator/debug.md
  doc/source/administrator/upgrading.md
  doc/source/jupyterhub/customizing/extending-jupyterhub.md
  doc/source/jupyterhub/installation.md
Labels: documentation

#2060 ci: stop accepting test failures in k8s 1.20
  .github/workflows/test-chart.yaml
Labels: ci

#2062 Fix spawner env injection example.
  doc/source/administrator/advanced.md
Labels: documentation

#2042 Make use of hub.existingSecret sustainable
  .github/workflows/test-chart.yaml
  ci/test-hub-existing-secret.yaml
  dev-config.yaml
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/files/hub/z2jh.py
  jupyterhub/schema.yaml
  jupyterhub/templates/_helpers-names.tpl
  jupyterhub/templates/hub/_helpers-passwords.tpl
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/hub/secret.yaml
  jupyterhub/templates/proxy/deployment.yaml
  tests/conftest.py
  tests/test_hub.py
  tests/test_spawn.py
Labels: breaking, enhancement

#2070 Fix schema validation for Spawner.cpu/memory limits/guarantees
  jupyterhub/schema.yaml
  jupyterhub/values.yaml
Labels: bug
