Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2021-05, with the labels that each got.

#2168 images/hub - a regular run of script: hub/images/dependencies freeze --upgrade
  images/hub/requirements.txt
Labels: dependencies

#2169 ci: accept 1 pod restart but not 2, test against k8s 1.21
  .github/workflows/test-chart.yaml
Labels: ci

#2173 inline comment: info about the state used by prePuller.hook.pullOnlyOnChanges
  jupyterhub/templates/image-puller/_helpers-daemonset.tpl
  jupyterhub/templates/image-puller/job.yaml
Labels: maintenance

#2174 fix: prePuller.hook.pullOnlyOnChanges didn't work, now it does
  jupyterhub/templates/hub/configmap.yaml
  jupyterhub/templates/image-puller/_helpers-daemonset.tpl
  jupyterhub/templates/image-puller/rbac.yaml
Labels: bug

#2176 bump traefik's and kube-scheduler's patch versions
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#2180 maint: revert a workaround to make our priorityclass resources helm hooks
  .github/workflows/test-chart.yaml
  jupyterhub/templates/scheduling/priorityclass.yaml
  jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
Labels: maintenance

#2182 Remove extraneous command from secret-sync image
  images/secret-sync/Dockerfile
Labels: maintenance

#2181 docs/ci: run template tests against least known supported helm version and document that version
  .github/workflows/test-chart.yaml
  doc/source/index.md
Labels: ci

#2186 ci: fix permissions of PR creating action
  .github/workflows/vuln-scan.yaml
Labels: ci

#2179 enable prePuller.hook.pullOnlyOnChanges by default
  doc/source/conf.py
  doc/source/index.md
  jupyterhub/values.yaml
Labels: maintenance

#2198 schema: added details to hub|singleuser.extraFiles
  jupyterhub/schema.yaml
Labels: maintenance

#2201 Pivot strategy (from breaking to non-breaking) to make our PriorityClass resources no longer be helm hook resources
  dev-config.yaml
  jupyterhub/templates/scheduling/priorityclass.yaml
  jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
Labels: breaking, bug

#2207 fix: respect hub.config entries to override seeded secrets
  jupyterhub/templates/hub/_helpers-passwords.tpl
Labels: bug

#2208 fix: remove no longer needed safeguard for enable_auth_state
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/_helpers.tpl
Labels: bug

#2209 refactor: stop manual hex-to-bytes conversion
  jupyterhub/files/hub/jupyterhub_config.py
Labels: maintenance

#2206 Minor documentation fixes
  doc/source/administrator/authentication.md
  jupyterhub/schema.yaml
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/hub/_helpers-passwords.tpl
  jupyterhub/templates/proxy/deployment.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: documentation

#2200 schema: catch typos in template values using JSONSchema's `additionalProperties`
  .github/workflows/test-chart.yaml
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/schema.yaml
  jupyterhub/templates/_helpers.tpl
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/image-pull-secret.yaml
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/deployment.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: breaking, enhancement

#2210 ci: print pip packages versions for debugging
  .github/workflows/publish.yml
Labels: ci

#2212 ci: update publish/test-chart workflow triggers
  .github/workflows/publish.yml
  .github/workflows/test-chart.yaml
Labels: ci

#2213 singleuser-sample: update base image
  .github/workflows/test-docker-build.yaml
  images/singleuser-sample/Dockerfile
Labels: dependencies, maintenance

#2215 Add debug.enabled to admin debugging doc
  doc/source/administrator/debug.md
Labels: documentation

#2225 docs: fix syntax error in markdown table
  jupyterhub/schema.yaml
Labels: documentation

#2230 docs: fix broken link
  doc/source/administrator/upgrading.md
Labels: documentation

#2211 Remove deprecated logic and emit clear messages
  doc/source/administrator/advanced.md
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/_helpers-auth-rework.tpl
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/hub/secret.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: breaking, maintenance

#2231 Bump CHP version to 4.4.0 (statsd dropped)
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#2226 docs: add documentation about resource requests
  doc/source/administrator/optimization.md
Labels: documentation

#2175 Add changelog for 1.0.0-beta.1
  CHANGELOG.md
  doc/source/administrator/advanced.md
  jupyterhub/schema.yaml
Labels: documentation
