Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2021-12, with the labels that each got.

#2505 bump jupyterhub to 2.0.0
  images/hub/requirements.in
  images/hub/requirements.txt
  images/singleuser-sample/requirements.txt
  jupyterhub/Chart.yaml
Labels: maintenance, dependencies

#2514 DOC: instructions for role creation in AWS
  doc/source/kubernetes/amazon/step-zero-aws-eks.md
  doc/source/kubernetes/amazon/step-zero-aws.md
Labels: documentation

#2519 Link to Discourse instead of the mailing list
  doc/source/administrator/upgrading.md
Labels: documentation

#2522 Don't pin example jupyter/minimal-notebook
  doc/source/jupyterhub/customizing/user-environment.md
Labels: documentation

#2524 deps: update traefik, kube-scheduler, and pause image
  jupyterhub/values.yaml
Labels: maintenance, dependencies

#2527 ci: remove workaround installing six
  .github/workflows/vuln-scan.yaml
Labels: ci

#2525 bump: jupyterhub 2.0.0 to 2.0.1
  images/hub/requirements.in
  images/hub/requirements.txt
  images/singleuser-sample/requirements.txt
  jupyterhub/Chart.yaml
Labels: maintenance, dependencies

#2526 Remove workaround to have PriorityClass resources as helm hooks
  jupyterhub/templates/scheduling/priorityclass.yaml
  jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
Labels: maintenance
