Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2021-07, with the labels that each got.

#2304 hub image: run apt-get upgrade by default to patch known vulns
  images/hub/Dockerfile
Labels: maintenance

#2305 Add ingress.pathType config
  jupyterhub/schema.yaml
  jupyterhub/templates/ingress.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement

#2306 Add configuration for arbitrary extra pod spec
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: new

#2307 Remove deprecation logic for hub.extraConfig as a string
  doc/source/administrator/advanced.md
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/schema.yaml
Labels: maintenance

#2309 ci: improve lint-and-validate-values.yaml coverage
  tools/templates/lint-and-validate-values.yaml
Labels: ci

#2310 fix: bug if z2jh is used as a dependency with an alias
  jupyterhub/templates/_helpers-names.tpl
Labels: bug

#2315 Bump patch version of: traefik, kube-scheduler, pause
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#2317 fix schema: accept proxy.traefik.extra[Static|Dynamic]Config
  jupyterhub/schema.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: bug

#2267 Docs clarification culling behavior and configs
  doc/source/administrator/advanced.md
  doc/source/jupyterhub/customizing/user-management.md
  jupyterhub/values.yaml
Labels: documentation

#2321 Bump CHP version to 4.5.0
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#2318 Allow CHP to function in a IPv4 only and/or IPv6 only context
  .github/workflows/test-chart.yaml
  jupyterhub/templates/proxy/deployment.yaml
Labels: bug

#2312 Seed hub.services' apiTokens
  CHANGELOG.md
  dev-config.yaml
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/_helpers-passwords.tpl
  jupyterhub/templates/hub/secret.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: breaking, enhancement

#2325 Add changelog for 1.1.0
  CHANGELOG.md
Labels: documentation

#2326 ci: misc fixes post 1.1.0
  .github/workflows/publish.yml
  .github/workflows/test-chart.yaml
  .github/workflows/test-docker-build.yaml
  dev-config.yaml
Labels: ci

#2327 fix hub.services schema regression from 1.1.0
  jupyterhub/schema.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: bug

#2331 docs: fix weird helm upgrade example
  doc/source/administrator/upgrading.md
Labels: documentation
