Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2021-09, with the labels that each got.

#2376 Remove no longer needed arm test adjustment
  dev-config-arm.yaml
Labels: ci

#2334 Documenting Microk8s cluster type.
  doc/source/kubernetes/other-infrastructure/step-zero-microk8s.md
  doc/source/kubernetes/setup-kubernetes.md
Labels: documentation

#2395 Tighten permissions for jupyterhub-idle-culler
  jupyterhub/files/hub/jupyterhub_config.py
Labels: maintenance

#2401 ci: use PVCs when testing upgrades
  .github/workflows/test-chart.yaml
Labels: ci

#2398 example configurations for UI choices
  doc/source/jupyterhub/customizing/user-environment.md
Labels: documentation

#2409 Update links that redirected
  .github/dependabot.yaml
  .github/workflows/publish.yml
  .github/workflows/test-chart.yaml
  .github/workflows/test-docker-build.yaml
  .github/workflows/test-docs.yaml
  .github/workflows/vuln-scan.yaml
Labels: documentation

#2404 ci: test against k8s 1.22
  .github/workflows/test-chart.yaml
Labels: ci

#2403 Add ingress.ingressClassName config option
  .github/workflows/test-chart.yaml
  jupyterhub/schema.yaml
  jupyterhub/templates/ingress.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement

#2411 Update NOTES.txt
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/_helpers.tpl
Labels: maintenance

#2418 ci: refresh circleci config
  .circleci/config.yml
Labels: ci
