Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2021-08, with the labels that each got.

#2343 additionalProperties should be set to True for templateVars in the schema
  doc/source/administrator/authentication.md
  jupyterhub/schema.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: bug

#2349 Add docs on GitHub team authentication
  doc/source/administrator/authentication.md
Labels: documentation

#2358 refactor: remove redundant trimSuffix of new lines after toYaml
  jupyterhub/templates/_helpers.tpl
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/hub/netpol.yaml
  jupyterhub/templates/hub/pvc.yaml
  jupyterhub/templates/image-puller/_helpers-daemonset.tpl
  jupyterhub/templates/image-puller/job.yaml
  jupyterhub/templates/ingress.yaml
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/autohttps/netpol.yaml
  jupyterhub/templates/proxy/autohttps/service.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/templates/proxy/netpol.yaml
  jupyterhub/templates/proxy/service.yaml
  jupyterhub/templates/scheduling/_scheduling-helpers.tpl
  jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml
  jupyterhub/templates/scheduling/user-scheduler/configmap.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/templates/singleuser/netpol.yaml
  tools/templates/yamllint-config.yaml
Labels: maintenance
