Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2021-04, with the labels that each got.

#2086 upload chart as github artifact
  .github/workflows/publish.yml
  .github/workflows/test-chart.yaml
Labels: ci, enhancement

#2142 Bump CHP from 4.3.1 to 4.3.2 for arm64 compatibility
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#2148 hub.service.extraPorts config option
  doc/source/administrator/index.md
  doc/source/administrator/services.md
  doc/source/kubernetes/amazon/step-zero-aws-eks.md
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/service.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: new

#2156 docs: fix docs build for breaking change in sphinx redirection extension
  doc/source/conf.py
Labels: maintenance

#2162 ci: update network tests as jupyter.org IPs changed
  dev-config.yaml
  tests/test_spawn.py
Labels: ci

#2165 Update NOTES.txt, including removing "alpha" designation
  jupyterhub/templates/NOTES.txt
Labels: maintenance

#2163 ci: precautions for security, update github_token permissions, pin actions
  .github/workflows/publish.yml
  .github/workflows/test-docker-build.yaml
  .github/workflows/vuln-scan.yaml
Labels: ci
