Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2021-03, with the labels that each got.

#2080 [DOC] Satisfy linkcheck
  .github/workflows/test-docs.yaml
  .readthedocs.yml
  CONTRIBUTING.md
  doc/README.md
  doc/requirements.txt
  doc/source/administrator/authentication.md
  doc/source/jupyterhub/installation.md
  doc/source/kubernetes/digital-ocean/step-zero-digital-ocean.md
  doc/source/resources/community.md
Labels: documentation

#2081 Bump CHP from 4.2.3 to 4.3.1
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#2083 ci: increase test timeout for test reliability
  tests/conftest.py
Labels: ci

#2066 Add prePuller.hook.pullOnlyOnChanges flag
  .github/workflows/test-chart.yaml
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/_helpers-passwords.tpl
  jupyterhub/templates/hub/configmap.yaml
  jupyterhub/templates/image-puller/_helpers-daemonset.tpl
  jupyterhub/templates/image-puller/daemonset-continuous.yaml
  jupyterhub/templates/image-puller/daemonset-hook.yaml
  jupyterhub/templates/image-puller/daemonset.yaml
  jupyterhub/templates/image-puller/job.yaml
  jupyterhub/values.yaml
Labels: enhancement

#2034 Don't set default resource requests
  jupyterhub/values.yaml
Labels: breaking, maintenance

#2090 Don't hard-code an old tag in customizing/user-environment.md
  doc/source/jupyterhub/customizing/user-environment.md
Labels: documentation

#2100 Fix mixup of hook/continuous-image-puller following recent PR
  jupyterhub/templates/image-puller/_helpers-daemonset.tpl
Labels: bug

#2105 Update postgres db url dialect in schema docs
  jupyterhub/schema.yaml
Labels: documentation

#2101 Enable opt-out of hub.jupyter.org/dedicated tolerations
  doc/source/administrator/optimization.md
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/image-puller/_helpers-daemonset.tpl
  jupyterhub/templates/image-puller/job.yaml
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/templates/scheduling/_scheduling-helpers.tpl
  jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement

#2109 Correct the AKS GPU Link in documentation
  doc/source/jupyterhub/customizing/user-resources.md
Labels: documentation
