Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2021-01, with the labels that each got.

#1968 docs: fix the dynamically set version of chart/jupyterhub
  doc/doc-requirements.txt
  doc/source/conf.py
  doc/source/index.md
  doc/source/index.rst
  doc/source/jupyterhub/customizing/extending-jupyterhub.rst
  doc/source/jupyterhub/installation.rst
  doc/source/repo2docker.rst
  doc/source/resources/community.rst
Labels: documentation

#1969 docs: remove unused config of esoteric sphinx builders
  doc/source/conf.py
Labels: documentation

#1970 pre-commit: chartpress --reset on Chart.yaml/values.yaml changes
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: maintenance

#1975 ci: run tests conditionally on changed paths
  .github/workflows/test-chart.yaml
  .github/workflows/test-docs.yaml
  README.md
Labels: maintenance

#1976 ci: linkcheck rework: avoid duplicated build, add colors, make it fail loud
  .github/workflows/test-docs.yaml
  doc/Makefile
  doc/make.bat
Labels: documentation

#1978 ci: add another upgrade test and provide a template rendering diff
  .github/workflows/test-chart.yaml
Labels: maintenance

#1980 ci: use extracted github action for namespace report
  .github/workflows/test-chart.yaml
  ci/common
Labels: ci

#1943 add hub.config passthrough and use it for all auth config
  .github/workflows/test-chart.yaml
  .github/workflows/test-docs.yaml
  doc/Makefile
  doc/make.bat
  doc/source/administrator/advanced.md
  doc/source/administrator/authentication.md
  doc/source/administrator/authentication.rst
  doc/source/administrator/optimization.md
  doc/source/administrator/security.md
  doc/source/conf.py
  images/hub/requirements.in
  images/hub/requirements.txt
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/schema.yaml
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/_helpers-auth-rework.tpl
  jupyterhub/templates/_helpers.tpl
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/hub/secret.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: breaking, maintenance

#1981 dep: bump kube-scheduler from 1.19.2 to 1.19.7
  ci/common
  dev-config.yaml
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#1983 k8s: update Ingress / PriorityClass apiVersions
  jupyterhub/templates/ingress.yaml
  jupyterhub/templates/scheduling/priorityclass.yaml
  jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
Labels: maintenance

#1985 ci: accept helm lint --strict failure, but ensure GitHub UI warns
  .github/workflows/test-chart.yaml
  tools/templates/lint-and-validate.py
Labels: ci

#1986 dep: bump traefik (autohttps pod) from v2.3.2 to v2.3.7
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#1926 Changelog for 0.11.0
  CHANGELOG.md
Labels: documentation

#1989 fix: fix of ingress regression and improved testing
  jupyterhub/templates/ingress.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: bug

#1991 Remove unused nameField helper in _helpers.tpl
  jupyterhub/templates/_helpers.tpl
Labels: maintenance

#1992 Also pull singleuser.initContainers with pre-puller
  jupyterhub/templates/image-puller/_daemonset-helper.yaml
Labels: enhancement

#1923 Support fullnameOverride / nameOverride and reference resources by named templates
  .github/workflows/test-chart.yaml
  ci/string-replacer.sh
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/files/hub/z2jh.py
  jupyterhub/schema.yaml
  jupyterhub/templates/_helpers-names.tpl
  jupyterhub/templates/_helpers.tpl
  jupyterhub/templates/hub/configmap.yaml
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/hub/netpol.yaml
  jupyterhub/templates/hub/pdb.yaml
  jupyterhub/templates/hub/pvc.yaml
  jupyterhub/templates/hub/rbac.yaml
  jupyterhub/templates/hub/secret.yaml
  jupyterhub/templates/hub/service.yaml
  jupyterhub/templates/image-pull-secret.yaml
  jupyterhub/templates/image-puller/_helpers-daemonset.tpl
  jupyterhub/templates/image-puller/daemonset.yaml
  jupyterhub/templates/image-puller/job.yaml
  jupyterhub/templates/image-puller/rbac.yaml
  jupyterhub/templates/ingress.yaml
  jupyterhub/templates/proxy/autohttps/configmap.yaml
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/autohttps/netpol.yaml
  jupyterhub/templates/proxy/autohttps/rbac.yaml
  jupyterhub/templates/proxy/autohttps/service.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/templates/proxy/netpol.yaml
  jupyterhub/templates/proxy/pdb.yaml
  jupyterhub/templates/proxy/secret.yaml
  jupyterhub/templates/proxy/service.yaml
  jupyterhub/templates/scheduling/priorityclass.yaml
  jupyterhub/templates/scheduling/user-placeholder/pdb.yaml
  jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
  jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml
  jupyterhub/templates/scheduling/user-scheduler/configmap.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/templates/scheduling/user-scheduler/pdb.yaml
  jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
  jupyterhub/templates/singleuser/netpol.yaml
  jupyterhub/values.yaml
  tools/templates/watch-diff.sh
Labels: enhancement

#1996 Autoformat bash scripts, yaml files, and markdown files with pre-commit
  .github/dependabot.yaml
  .github/workflows/publish.yml
  .github/workflows/test-chart.yaml
  .github/workflows/test-docs.yaml
  .github/workflows/vuln-scan.yaml
  .pre-commit-config-shellcheck.yaml
  .pre-commit-config.yaml
  .prettierignore
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  RELEASE.md
  ci/common
  dev-config.yaml
  dev-requirements.txt
  doc/source/_static/custom.css
  doc/source/administrator/advanced.md
  doc/source/administrator/authentication.md
  doc/source/administrator/cost.md
  doc/source/administrator/debug.md
  doc/source/administrator/optimization.md
  doc/source/administrator/security.md
  doc/source/administrator/troubleshooting.md
  doc/source/administrator/upgrading.md
  doc/source/index.md
  doc/source/jupyterhub/customizing/extending-jupyterhub.md
  doc/source/jupyterhub/customizing/user-environment.md
  doc/source/jupyterhub/customizing/user-management.md
  doc/source/jupyterhub/customizing/user-resources.md
  doc/source/jupyterhub/customizing/user-storage.md
  doc/source/jupyterhub/installation.md
  doc/source/jupyterhub/uninstall.md
  doc/source/kubernetes/amazon/efs_storage.md
  doc/source/kubernetes/amazon/step-zero-aws-eks.md
  doc/source/kubernetes/amazon/step-zero-aws.md
  doc/source/kubernetes/digital-ocean/step-zero-digital-ocean.md
  doc/source/kubernetes/google/step-zero-gcp.md
  doc/source/kubernetes/ibm/step-zero-ibm.md
  doc/source/kubernetes/microsoft/step-zero-azure-autoscale.md
  doc/source/kubernetes/microsoft/step-zero-azure.md
  doc/source/kubernetes/ovh/step-zero-ovh.md
  doc/source/kubernetes/setup-helm.md
  doc/source/kubernetes/setup-helm2.md
  doc/source/repo2docker.md
  doc/source/resources/community.md
  doc/source/resources/glossary.md
  doc/source/resources/reference-docs.md
  doc/source/resources/tools.md
  images/image-awaiter/README.md
  images/singleuser-sample/README.md
  jupyterhub/Chart.yaml
  jupyterhub/files/userscheduler-defaultpolicy.yaml
  jupyterhub/schema.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
  tools/templates/yamllint-config.yaml
Labels: maintenance

#2004 ci: accept k8s 1.20 failures until 1.20.3 is out
  .github/workflows/test-chart.yaml
Labels: ci

#1994 Require Helm 3 to allow for enhancements
  jupyterhub/Chart.yaml
Labels: breaking, maintenance

#2003 refactor: systematically prefer use of with in templates
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/hub/pvc.yaml
  jupyterhub/templates/ingress.yaml
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/templates/proxy/service.yaml
  jupyterhub/templates/scheduling/_scheduling-helpers.tpl
Labels: maintenance

#2008 refactor: consistently use toYaml with annotations/labels
  jupyterhub/templates/proxy/autohttps/service.yaml
Labels: maintenance

#2010 cleanup: remove mistakenly added artifactshub.io config file
  artifacthub-repo.yml
Labels: maintenance

#1993 Seed secrets (proxy.secretToken, etc) so they don't have to be manually generated
  .github/workflows/test-chart.yaml
  dev-config.yaml
  doc/source/administrator/debug.md
  doc/source/jupyterhub/installation.md
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/files/hub/z2jh.py
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/_helpers-passwords.tpl
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/hub/secret.yaml
  jupyterhub/templates/proxy/deployment.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: new

#2007 fix: set tolerations to predefined labels on core pods
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/image-puller/job.yaml
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
Labels: bug

#2017 ci: use yq to parse version from Chart.yaml and save ~30 seconds
  .github/workflows/test-chart.yaml
Labels: ci

#2018 ci: stop using --long as chartpress 1.0.0 makes it not needed
  ci/publish
Labels: ci

#2016 Followup fixes to seed secrets PR (#1993)
  .github/workflows/test-chart.yaml
  jupyterhub/templates/hub/_helpers-passwords.tpl
Labels: bug
