Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2021-06, with the labels that each got.

#2243 Test against k8s 1.21 and avoid deprecation warning for old k8s api policy/v1beta1
  .github/workflows/test-chart.yaml
  jupyterhub/templates/hub/pdb.yaml
  jupyterhub/templates/proxy/autohttps/pdb.yaml
  jupyterhub/templates/proxy/pdb.yaml
  jupyterhub/templates/scheduling/user-placeholder/pdb.yaml
  jupyterhub/templates/scheduling/user-scheduler/pdb.yaml
Labels: ci, maintenance

#2236 Add annotations to rbac serviceAccount
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/rbac.yaml
  jupyterhub/templates/image-puller/rbac.yaml
  jupyterhub/templates/proxy/autohttps/rbac.yaml
  jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement

#2249 Update installation.md
  doc/source/jupyterhub/installation.md
Labels: documentation

#2248 Add participation in study notice to readme
  README.md
Labels: documentation

#2251 Fix fullnameOverride for Ingress & PriorityClass resources
  jupyterhub/templates/_helpers-names.tpl
Labels: bug

#2262 hub image: add sqlalchemy-cocroachdb dependency
  images/hub/requirements.in
  images/hub/requirements.txt
Labels: dependencies, maintenance

#2273 Remove pre-commit from GHA
  .github/workflows/test-chart.yaml
Labels: ci

#2278 Transition to use pre-commit hook in jupyterhub/chartpress
  .pre-commit-config.yaml
Labels: ci

#2268 added AWS EKS cluster scaling/auto-scaling documentation for z2jh
  doc/source/jupyterhub/customizing/user-resources.md
Labels: documentation

#2284 templates: quote namespace in case they are only contain numbers
  doc/source/administrator/advanced.md
  jupyterhub/templates/hub/rbac.yaml
  jupyterhub/templates/image-puller/rbac.yaml
  jupyterhub/templates/scheduling/priorityclass.yaml
  jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
  jupyterhub/templates/scheduling/user-scheduler/configmap.yaml
  jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
Labels: bug

#2283 schema: force labels and annotations to be strings
  jupyterhub/schema.yaml
Labels: maintenance

#2285 Relax hub.db.type schema to accept unknown database types
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/schema.yaml
Labels: bug

#2286 singleuser-sample image: bump base image to reduce known vulns
  images/singleuser-sample/Dockerfile
Labels: dependencies, maintenance

#2288 Bump traefik from 2.4.8 to 2.4.9
  jupyterhub/values.yaml
Labels: dependencies, maintenance

#2289 Relax extraEnv schema to allow for array values
  jupyterhub/schema.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: bug

#2287 Add changelog for 1.0.1
  CHANGELOG.md
Labels: documentation

#2293 Fix failure to set imagePullSecrets for user-placeholder pods (scheduling.userPlaceholder.image config added)
  jupyterhub/schema.yaml
  jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: bug
