Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2022-11, with the labels that each got.

#2909 docs: update of readthedocs config and docs/source/conf.py
  .readthedocs.yaml
  .readthedocs.yml
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation

#2920 Add a jupyterhub/k8s-hub-slim image alongside jupyterhub/k8s-hub
  .github/workflows/test-chart.yaml
  chartpress.yaml
  docs/source/administrator/security.md
  images/hub/Dockerfile
  images/hub/requirements.in
  images/hub/requirements.txt
  images/singleuser-sample/Dockerfile
Labels: new

#2919 Upgrade from python 3.9 to 3.11 in hub and singleuser-sample for performance
  .github/workflows/test-chart.yaml
  .github/workflows/test-docker-build.yaml
  .github/workflows/test-docs.yaml
  .github/workflows/vuln-scan.yaml
  .github/workflows/watch-dependencies.yaml
  ci/refreeze
  images/hub/Dockerfile
  images/hub/requirements.txt
  images/secret-sync/Dockerfile
  images/singleuser-sample/Dockerfile
  images/singleuser-sample/requirements.txt
Labels: maintenance

#2936 Drop support for k8s 1.20
  .github/workflows/test-chart.yaml
  docs/source/changelog.md
  jupyterhub/Chart.yaml
  jupyterhub/templates/hub/pdb.yaml
  jupyterhub/templates/proxy/autohttps/pdb.yaml
  jupyterhub/templates/proxy/pdb.yaml
  jupyterhub/templates/scheduling/user-placeholder/pdb.yaml
  jupyterhub/templates/scheduling/user-scheduler/configmap.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/templates/scheduling/user-scheduler/pdb.yaml
  jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
Labels: breaking, maintenance

#2939 ci: minimize yamllint-config.yaml's complexity
  tools/templates/yamllint-config.yaml
Labels: ci

#2938 ci: minor refactoring/updates of tools
  tools/compare-values-schema-content.py
  tools/generate-json-schema.py
  tools/templates/lint-and-validate.py
  tools/validate-against-schema.py
Labels: ci

#2940 pre-commit: add flake8 and fix details
  .pre-commit-config.yaml
  images/secret-sync/acme-secret-sync.py
  jupyterhub/files/hub/jupyterhub_config.py
  tests/conftest.py
  tests/test_hub.py
  tests/test_spawn.py
Labels: maintenance

#2941 Update kube-scheduler to v1.25 and its configuration api to v1 if k8s >=1.24
  .github/workflows/watch-dependencies.yaml
  jupyterhub/templates/scheduling/user-scheduler/configmap.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: maintenance

#2943 ci: fix deprecation of set-output in github workflows
  .github/workflows/vuln-scan.yaml
  .github/workflows/watch-dependencies.yaml
Labels: ci

#2956 docs: AWS master node size needs to be larger than micro
  docs/source/kubernetes/amazon/step-zero-aws.md
Labels: documentation
