Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2022-03, with the labels that each got.

#2613 hub image: bump jupyterhub to 2.2.0 and refreeze dependencies
  images/hub/requirements.in
  images/hub/requirements.txt
  jupyterhub/Chart.yaml
Labels: maintenance, dependencies

#2618 Add support bot
  .github/workflows/support-bot.yml
Labels: ci

#2630 update step-zero-microk8s.md
  docs/source/kubernetes/other-infrastructure/step-zero-microk8s.md
Labels: documentation

#2628 Fix failure to respect proxy.secretSync.resources configuration
  jupyterhub/templates/proxy/autohttps/deployment.yaml
Labels: bug

#2635 Require k8s 1.20+ and small cleanups based on assuming it
  .github/workflows/test-chart.yaml
  docs/source/administrator/advanced.md
  docs/source/resources/glossary.md
  jupyterhub/Chart.yaml
  jupyterhub/schema.yaml
  jupyterhub/templates/hub/pdb.yaml
  jupyterhub/templates/ingress.yaml
  jupyterhub/templates/proxy/autohttps/pdb.yaml
  jupyterhub/templates/proxy/pdb.yaml
  jupyterhub/templates/scheduling/user-placeholder/pdb.yaml
  jupyterhub/templates/scheduling/user-scheduler/pdb.yaml
Labels: breaking, maintenance
