Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2022-02, with the labels that each got.

#2562 image-awaiter: fix known vulns. by updating to golang:1.17 in image build stage
  images/image-awaiter/Dockerfile
Labels: maintenance, dependencies

#2600 Fix broken internal references in docs
  docs/requirements.txt
  docs/source/administrator/optimization.md
  docs/source/administrator/upgrading.md
  docs/source/resources/community.md
Labels: documentation

#2603 Remove typo " in schema.yaml
  jupyterhub/schema.yaml
Labels: bug

#2604 Use chart logo from https://jupyterhub.github.io/helm-chart
  docs/source/_static/images/logo/hublogo.svg
  jupyterhub/Chart.yaml
Labels: maintenance

#2590 Update user-scheduler's kube-scheduler binary and config when in k8s clusters versioned >=1.21
  .github/workflows/test-chart.yaml
  jupyterhub/schema.yaml
  jupyterhub/templates/scheduling/user-scheduler/configmap.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: breaking, maintenance
