Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2022-05, with the labels that each got.

#2640 docs: Remove a false promise regarding CHOWN_HOME
  docs/source/kubernetes/amazon/efs_storage.md
Labels: documentation

#2681 Enable image-puller pods to evict user-placeholder pods
  jupyterhub/schema.yaml
  jupyterhub/templates/_helpers-names.tpl
  jupyterhub/templates/image-puller/_helpers-daemonset.tpl
  jupyterhub/templates/image-puller/priorityclass.yaml
  jupyterhub/values.yaml
Labels: bug

#2694 ci: add automation to update chp and traefik images
  .github/workflows/watch-image-dependencies.yaml
Labels: ci

#2698 ci: automatically bump kube-scheduler and pause image tags
  .github/workflows/watch-dependencies.yaml
  jupyterhub/values.yaml
Labels: ci

#2707 ci: fix syntax error in dependabot config
  .github/dependabot.yaml
Labels: ci

#2709 ci: use jupyterhub-bot PAT to trigger github workflow on opened PRs
  .github/workflows/vuln-scan.yaml
  .github/workflows/watch-dependencies.yaml
Labels: ci

#2517 docs: document `singleuser.someConfig` by linking to `KubeSpawner.some_config` docs
  jupyterhub/schema.yaml
Labels: documentation

#2713 Add singleuser.allowPrivilegeEscalation for KubeSpawner 2+
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/schema.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: new

#2697 docs: how to adjust profile_list dynamically based on user etc
  docs/source/jupyterhub/customizing/user-environment.md
Labels: documentation

#2720 breaking: add hub.podSecurityContext, remove hub.fsGid
  jupyterhub/schema.yaml
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/values.yaml
Labels: breaking, new

#2725 Bump versions of image-awaiter dependencies
  images/image-awaiter/Dockerfile
  images/image-awaiter/go.mod
  images/image-awaiter/go.sum
Labels: maintenance, dependencies

#2717 Add opengraph tags
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation

#2729 ci: reduce frequency of gha/vuln bumps
  .github/dependabot.yaml
  .github/workflows/vuln-scan.yaml
Labels: ci

#2727 Fix for PDBs in k8s 1.20
  .github/dependabot.yaml
  jupyterhub/templates/hub/pdb.yaml
  jupyterhub/templates/proxy/autohttps/pdb.yaml
  jupyterhub/templates/proxy/pdb.yaml
  jupyterhub/templates/scheduling/user-placeholder/pdb.yaml
  jupyterhub/templates/scheduling/user-scheduler/pdb.yaml
Labels: bug

#2732 maint: update import statement for py310 compatibility
  jupyterhub/files/hub/z2jh.py
Labels: maintenance
