Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2022-08, with the labels that each got.

#2820 Restore jupyterhub-singleuser as the default command
  docs/source/administrator/upgrading/upgrade-1-to-2.md
  docs/source/jupyterhub/customizing/user-environment.md
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/schema.yaml
  jupyterhub/values.yaml
Labels: breaking, maintenance

#2821 Fix step-zero-ovh 404
  docs/source/kubernetes/ovh/step-zero-ovh.md
Labels: documentation

#2826 ci: remove dependabot bumping for hub image's req file
  .github/dependabot.yaml
Labels: ci

#2838 ci: remove no longer needed workaround for action-k3s-helm
  .github/workflows/test-chart.yaml
Labels: ci

#2842 ci: add workaround for k3s in circleci tests as well
  .circleci/config.yml
Labels: ci

#2823 Update docs to reflect Azure 2022 process
  docs/source/_static/images/azure/scale_condition.png
  docs/source/_static/images/azure/scale_in.png
  docs/source/_static/images/azure/scale_out.png
  docs/source/conf.py
  docs/source/jupyterhub/installation.md
  docs/source/kubernetes/microsoft/step-zero-azure-autoscale.md
  docs/source/kubernetes/microsoft/step-zero-azure.md
  docs/source/kubernetes/setup-kubernetes.md
Labels: documentation

#2528 docs: add changelog for 2.0.0 (beta.1)
  docs/source/administrator/upgrading/upgrade-1-to-2.md
  docs/source/changelog.md
Labels: documentation

#2845 Make the singleuser-sample image use python:3.9-slim-bullseye as a base image to retain arm64 support
  .circleci/config.yml
  .github/workflows/watch-dependencies.yaml
  ci/refreeze
  images/hub/Dockerfile
  images/hub/requirements.txt
  images/singleuser-sample/Dockerfile
  images/singleuser-sample/requirements.in
  images/singleuser-sample/requirements.txt
Labels: breaking, maintenance

#2853 Corrected indentation in the config.yml example
  docs/source/jupyterhub/customizing/user-environment.md
Labels: documentation
