Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2022-07, with the labels that each got.

#2787 Adjust kerning on large JupyterHub in NOTES.txt
  jupyterhub/templates/NOTES.txt
Labels: maintenance

#2785 Test postgres schema upgrade in CI
  .github/workflows/test-chart.yaml
  ci/common
  dev-config.yaml
  docs/source/administrator/upgrading/index.md
Labels: ci

#2790 docs: fix most broken links in changelog
  docs/source/changelog.md
  docs/source/kubernetes/microsoft/step-zero-azure-autoscale.md
  docs/source/kubernetes/redhat/step-zero-openshift.md
  images/image-awaiter/README.md
  images/singleuser-sample/README.md
Labels: documentation

#2791 Add `labels` config for `scheduling.userScheduler`, `scheduling.userPlaceholder`, and `prePuller`
  jupyterhub/schema.yaml
  jupyterhub/templates/image-puller/job.yaml
  jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/values.yaml
Labels: new

#2815 Replace jhub with <k8s-namespace> for consistency
  docs/source/jupyterhub/installation.md
Labels: documentation

#2810 Add breaking KubeSpawner changes to upgrade-1-to-2
  docs/source/administrator/upgrading/upgrade-1-to-2.md
Labels: documentation
