Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2022-09, with the labels that each got.

#2856 Mount wheels from build stage instead of copying
  .circleci/config.yml
  .github/workflows/test-chart.yaml
  images/hub/Dockerfile
  images/singleuser-sample/Dockerfile
Labels: maintenance

#2859 ci: disable dependabot bumping singleuser-sample deps
  .github/dependabot.yaml
Labels: ci

#2860 Update chartpress to 2.1+ and adopt tbump in the release process
  RELEASE.md
  chartpress.yaml
  dev-requirements.txt
  tbump.toml
Labels: maintenance

#2855 Update changelog for 2.0.0
  docs/source/changelog.md
Labels: documentation

#2877 docs: auth defaults to dummy
  docs/source/administrator/authentication.md
Labels: documentation

#2878 docs: remove /auth from keycloak URLs
  docs/source/administrator/authentication.md
Labels: documentation

#2879 docs: fix git sha lookup for dev builds
  docs/source/conf.py
Labels: documentation

#2881 values.yaml: fix link to configurable-http-proxy releases
  jupyterhub/values.yaml
Labels: maintenance

#2862 docs: backfill early changelog entries based on git tags and github releases
  docs/source/changelog.md
Labels: documentation
