Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2022-01, with the labels that each got.

#2543 Replace zone to allowedTopologies
  docs/source/jupyterhub/customizing/user-storage.md
Labels: documentation

#2548 ci: test against k8s 1.23
  .github/workflows/test-chart.yaml
Labels: ci

#2546 Enable parent chart's (binderhub etc) to use imagePullSecrets helper
  jupyterhub/templates/_helpers.tpl
Labels: enhancement

#2555 bump JupyterHub from 2.0.2 to 2.1.1
  images/hub/requirements.in
  images/hub/requirements.txt
  images/singleuser-sample/requirements.txt
  jupyterhub/Chart.yaml
Labels: maintenance, dependencies

#2554 Improved nodeSelector formatting in template
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/image-puller/_helpers-daemonset.tpl
  jupyterhub/templates/image-puller/job.yaml
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
Labels: maintenance
