Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2022-06, with the labels that each got.

#2508 breaking: add ...networkPolicy.egressAllowRules and don't allow singleuser pods to access PrivateIPv4 addresses by default
  dev-config-local-chart-extra-config.yaml
  dev-config.yaml
  docs/source/administrator/security.md
  jupyterhub/schema.yaml
  jupyterhub/templates/_helpers-netpol.tpl
  jupyterhub/templates/hub/netpol.yaml
  jupyterhub/templates/proxy/autohttps/netpol.yaml
  jupyterhub/templates/proxy/netpol.yaml
  jupyterhub/templates/singleuser/netpol.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: breaking, maintenance

#2730 maint: add pre-commit isort hook, and let pyupgrade assume py38+ in hub container
  .pre-commit-config.yaml
  docs/source/conf.py
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/files/hub/z2jh.py
  tests/conftest.py
  tools/compare-values-schema-content.py
  tools/generate-json-schema.py
  tools/set-chart-yaml-annotations.py
  tools/templates/lint-and-validate.py
  tools/validate-against-schema.py
Labels: maintenance

#2719 maint: cleanup deprecation warning introduced in 0.10.0 (assume users upgrade to v2 from v1)
  jupyterhub/templates/NOTES.txt
Labels: maintenance

#2578 Support idle culler --cull-admin-users
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/schema.yaml
  jupyterhub/values.yaml
Labels: new

#2741 hub image: downgrade to ltiauthenticator 1.2.0
  images/hub/requirements.in
  images/hub/requirements.txt
Labels: maintenance, dependencies

#2739 breaking, maint: replace rbac.enabled with rbac.create
  docs/source/administrator/security.md
  jupyterhub/schema.yaml
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/_helpers.tpl
  jupyterhub/templates/hub/rbac.yaml
  jupyterhub/templates/image-puller/rbac.yaml
  jupyterhub/templates/proxy/autohttps/rbac.yaml
  jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: breaking, maintenance

#2748 ci: add a refreeze requirements.txt job and use dedicated gha env
  .github/workflows/vuln-scan.yaml
  .github/workflows/watch-dependencies.yaml
  images/hub/README.md
Labels: ci

#2762 Add scheduling.userPlaceholder.annotations
  jupyterhub/schema.yaml
  jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml
  jupyterhub/values.yaml
Labels: new

#2763 Add scheduling.userScheduler.annotations
  jupyterhub/schema.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
  jupyterhub/values.yaml
Labels: new

#2769 docs: move changelog from pure markdown to sphinx based docs
  CHANGELOG.md
  RELEASE.md
  docs/source/administrator/upgrading.md
  docs/source/changelog.md
  docs/source/conf.py
  docs/source/index.md
Labels: documentation
