Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2023-08, with the labels that each got.

#3179 Add and enable two egressAllowRules to ensure DNS access
  jupyterhub/templates/_helpers-netpol.tpl
  jupyterhub/values.schema.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: new

#3192 maint: restrict allowed config with blockWithIpTables, add misc docs
  docs/source/administrator/security.md
  docs/source/changelog.md
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/templates/NOTES.txt
  jupyterhub/templates/_helpers-netpol.tpl
  jupyterhub/values.schema.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: breaking, maintenance

#3191 maint: cleanup in development chart config files
  .github/workflows/test-chart.yaml
  dev-config-local-chart-extra-config.yaml
  dev-config.yaml
Labels: maintenance

#3196 Update changelog for 3.0.0
  docs/source/changelog.md
Labels: documentation

#3200 docs: fix the jupyterhub managed service example's networking rules
  docs/source/administrator/services.md
Labels: documentation

#3201 Add changelog for 3.0.1
  docs/source/changelog.md
  docs/source/jupyterhub/customizing/user-storage.md
Labels: documentation

#3204 Add changelog for 3.0.2
  docs/requirements.txt
  docs/source/administrator/optimization.md
  docs/source/changelog.md
Labels: documentation

#3209 Add changelog for 3.0.3
  docs/source/changelog.md
Labels: documentation

#3211 docs: fix changelog date entry for 3.0.3
  docs/source/changelog.md
Labels: documentation
