Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2023-03, with the labels that each got.

#3041 Drop support for k8s 1.21
  .github/workflows/test-chart.yaml
  docs/source/changelog.md
  images/hub/Dockerfile
  images/singleuser-sample/Dockerfile
  jupyterhub/Chart.yaml
  jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
Labels: breaking, maintenance

#3048 docs: Replace most permanent-redirects from linkcheck
  docs/source/administrator/authentication.md
  docs/source/administrator/upgrading/index.md
  docs/source/jupyterhub/customizing/user-resources.md
  docs/source/kubernetes/amazon/step-zero-aws-eks.md
  docs/source/kubernetes/google/step-zero-gcp.md
  docs/source/kubernetes/microsoft/step-zero-azure.md
  docs/source/resources/glossary.md
  docs/source/resources/reference-docs.md
Labels: documentation

#3049 Use jupyterhub docs `stable` instead of `latest`
  docs/source/administrator/authentication.md
  docs/source/administrator/upgrading/upgrade-1-to-2.md
  docs/source/changelog.md
  docs/source/resources/glossary.md
  docs/source/resources/reference-docs.md
  jupyterhub/schema.yaml
Labels: documentation

#3050 Revert https://app.gitter.im/#/room/#jupyterhub_jupyterhub:gitter.im …
  docs/source/administrator/upgrading/index.md
Labels: documentation

#3051 Summarise linkcheck CI output
  .github/workflows/test-docs.yaml
  ci/summarise-linkcheck-output
Labels: ci

#3047 docs: user-env default image is not base-image
  docs/source/jupyterhub/customizing/user-environment.md
Labels: documentation

#3055 Replace microk8s with generic self-hosted doc
  docs/source/conf.py
  docs/source/kubernetes/other-infrastructure/.gitkeep
  docs/source/kubernetes/other-infrastructure/step-zero-microk8s.md
  docs/source/kubernetes/other-infrastructure/step-zero-other.md
  docs/source/kubernetes/setup-kubernetes.md
Labels: documentation

#3003 docs: Update custom image docs to reflect root requirement
  docs/source/administrator/services.md
Labels: documentation

#3032 Fix bugs related to installing chart multiple times in the same namespace
  jupyterhub/templates/_helpers-names.tpl
  jupyterhub/templates/proxy/service.yaml
Labels: bug

#3065 satisfy flake8 in jupyterhub_config.py
  .flake8
  .pre-commit-config.yaml
  jupyterhub/files/hub/jupyterhub_config.py
Labels: maintenance

#3068 ci: fix deprecation of set-output and use ubuntu 22.04 and py311
  .github/workflows/publish.yml
  .github/workflows/release-tag.yml
  .github/workflows/support-bot.yml
  .github/workflows/test-docker-build.yaml
  .github/workflows/test-docs.yaml
  .github/workflows/vuln-scan.yaml
  .github/workflows/watch-dependencies.yaml
Labels: ci

#3073 Replace IEC prefixes link
  docs/source/jupyterhub/customizing/user-storage.md
Labels: documentation

#3079 doc: singleuser.uid default is always 1000
  jupyterhub/schema.yaml
Labels: documentation
