Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2023-11, with the labels that each got.

#3256 ci: fetch stable/dev releases using helm show to avoid cache issues
  .github/workflows/test-chart.yaml
Labels: ci

#3217 Pull images from `singleuser.profileList` found in `profile_options.choices`
  docs/source/conf.py
  jupyterhub/templates/image-puller/_helpers-daemonset.tpl
  jupyterhub/values.schema.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement

#3272 Publish to Docker Hub alongside Quay.io
  .github/workflows/publish.yml
  .pre-commit-config.yaml
  ci/publish
  docs/source/changelog.md
Labels: maintenance

#3277 Add changelog for 3.2.0
  docs/source/changelog.md
Labels: documentation

#3278 Update oauthenticator from 16.2.0 to 16.2.1
  images/hub/requirements.txt
Labels: documentation

#3279 Add changelog for 3.2.1
  docs/source/changelog.md
Labels: documentation
