Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2023-07, with the labels that each got.

#3149 Add changelog for 3.0.0-beta.2
  docs/source/administrator/authentication.md
  docs/source/changelog.md
Labels: documentation

#3151 docs: let auth docs link to authenticator specific docs
  docs/source/administrator/authentication.md
  docs/source/conf.py
Labels: documentation

#3153 Update oauthenticator from 16.0.1 to 16.0.2
  images/hub/requirements.txt
Labels: maintenance

#3154 Add changelog for 3.0.0-beta.3
  docs/source/changelog.md
Labels: documentation

#3162 Allow `enabled` config, for use by charts depending on this chart conditionally
  docs/source/conf.py
  jupyterhub/values.schema.yaml
  jupyterhub/values.yaml
Labels: enhancement

#3168 Include shellcheck pre-commit in main pre-commit
  .github/workflows/test-chart.yaml
  .pre-commit-config-shellcheck.yaml
  .pre-commit-config.yaml
Labels: ci
