Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2024-09, with the labels that each got.

#3492 Add `ingress.extraPaths` config
  jupyterhub/templates/ingress.yaml
  jupyterhub/values.schema.yaml
  jupyterhub/values.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: new

#3514 user-scheduler: update kube-scheduler binary from 1.28.14 to 1.30.5
  docs/source/changelog.md
  jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
  jupyterhub/values.yaml
Labels: maintenance

#3517 ci: configure automatic bump of kube-scheduler to version 1.30.x
  .github/workflows/watch-dependencies.yaml
Labels: ci

#3519 Bump oauthenticator from 16.3.1 to 17.0.0
  docs/source/changelog.md
  images/hub/requirements.txt
Labels: breaking, new

#3520 Bump kubespawner from 6.2.0 to 7.0.0b1
  docs/source/changelog.md
  images/hub/requirements.in
  images/hub/requirements.txt
Labels: breaking, maintenance

#3521 Add backdated upgrade guide for 2 to 3
  docs/source/administrator/upgrading/index.md
  docs/source/administrator/upgrading/upgrade-2-to-3.md
Labels: documentation

#3523 Add oauthenticator googlegroups extras and cleanup dependencies
  images/hub/requirements.in
  images/hub/requirements.txt
  images/singleuser-sample/requirements.txt
Labels: new
