Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2024-10, with the labels that each got.

#3522 Add changelog for 4.0.0-beta.1
  docs/source/administrator/upgrading/index.md
  docs/source/administrator/upgrading/upgrade-1-to-2.md
  docs/source/administrator/upgrading/upgrade-2-to-3.md
  docs/source/administrator/upgrading/upgrade-3-to-4.md
  docs/source/changelog.md
Labels: documentation

#3526 Use python 3.12 instead of 3.11 in built images
  ci/refreeze
  images/hub/Dockerfile
  images/secret-sync/Dockerfile
  images/singleuser-sample/Dockerfile
Labels: breaking, maintenance

#3529 kubespawner 7.0.0b2
  images/hub/requirements.in
  images/hub/requirements.txt
Labels: bug

#3534 add appProtocol to hub service definition
  jupyterhub/templates/hub/service.yaml
  jupyterhub/values.schema.yaml
  jupyterhub/values.yaml
Labels: new

#3542 Update oauthenticator from 17.0.0 to 17.1.0
  images/hub/requirements.txt
Labels: maintenance, dependencies

#3544 Update ldapauthenticator from 1.3.2 to 2.0.0.b2
  images/hub/requirements.in
  images/hub/requirements.txt
Labels: dependencies

#3543 Add changelog for 4.0.0-beta.4
  docs/source/changelog.md
Labels: documentation

#3546 Ensure hub container is first by appending instead of prepending hub.extraContainers
  jupyterhub/templates/hub/deployment.yaml
Labels: maintenance

#3554 ci: Bump postgresql chart
  .github/workflows/test-chart.yaml
Labels: ci

#3548 Support subdomain_host (CHP needs --host-routing)
  .github/workflows/test-chart.yaml
  docs/source/administrator/security.md
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/values.schema.yaml
  tests/test_spawn.py
Labels: new

#3558 remove maintenance label from autobump PRs
  .github/workflows/watch-dependencies.yaml
Labels: maintenance

#3562 Update kubespawner ldapauthenticator
  images/hub/requirements.in
Labels: dependencies
