Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2024-07, with the labels that each got.

#3461 RTD custom domain changes
  docs/source/conf.py
Labels: documentation

#3468 Add `singleuser.storage.dynamic.subPath` config
  jupyterhub/files/hub/jupyterhub_config.py
  jupyterhub/values.schema.yaml
  jupyterhub/values.yaml
Labels: new

#3471 Update jupyterhub from 4.1.5 to 4.1.6
  images/hub/requirements.in
  images/hub/requirements.txt
  images/singleuser-sample/requirements.in
  images/singleuser-sample/requirements.txt
  jupyterhub/Chart.yaml
Labels: maintenance

#3473 Add changelog for 3.3.8
  docs/source/changelog.md
Labels: documentation
