Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2024-03, with the labels that each got.

#3357 Fix previously ignored revisionHistoryLimit config
  jupyterhub/templates/hub/deployment.yaml
  jupyterhub/templates/image-puller/_helpers-daemonset.tpl
  jupyterhub/templates/proxy/autohttps/deployment.yaml
  jupyterhub/templates/proxy/deployment.yaml
  jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml
  jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
Labels: bug

#3364 Add changelog for 3.3.0
  docs/source/changelog.md
Labels: documentation

#3367 Add changelog for 3.3.1
  docs/source/changelog.md
Labels: documentation

#3369 network-tools image: pin alpine 3.18 for legacy iptables
  images/network-tools/Dockerfile
Labels: bug

#3371 unpin pycurl
  images/hub/Dockerfile
  images/hub/requirements.in
  images/hub/requirements.txt
Labels: maintenance

#3376 Add changelog for 3.3.3
  docs/source/changelog.md
Labels: documentation

#3382 Add changelog for 3.3.5
  docs/source/administrator/security.md
  docs/source/changelog.md
Labels: documentation

#3385 Add changelog for 3.3.6
  docs/source/changelog.md
Labels: documentation
