Repository jupyterhub/zero-to-jupyterhub-k8s, pull requests merged in 2025-04, with the labels that each got.

#3651 ci: update watch dependencies workflow to function again
  .github/workflows/watch-dependencies.yaml
Labels: ci

#3654 Linkcheck: update ignored and permanently redirected external URLs
  docs/source/administrator/authentication.md
  docs/source/administrator/cost.md
  docs/source/conf.py
  docs/source/index.md
  docs/source/kubernetes/amazon/step-zero-aws.md
  docs/source/kubernetes/redhat/step-zero-openshift.md
  docs/source/repo2docker.md
  jupyterhub/values.schema.yaml
Labels: documentation

#3655 Replace deprecated `pipes.quote` with `shlex.quote`
  tools/templates/lint-and-validate.py
Labels: maintenance

#3653 Add changelog for 4.2.0
  docs/source/changelog.md
Labels: documentation
